
services:
  aratech-vitrine:
    image: aratechia/vitrine:local
    build:
      context: ../
      dockerfile: docker-local/Dockerfile-dev
    container_name: aratech-vitrine
    command: |
      sh -c "
      python /App/manage.py collectstatic && python /App/manage.py migrate && /App/start.sh
      "
    env_file:
      - .env
    volumes:
      - ${APP_DIR}:/App
    ports:
      - "8000:9090"

